<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="5" failed="0" ignored="0" total="9" passed="4">
  <reporter-output>
    <line>
      <![CDATA[<a href='C:\eclipse-workspace\project\screenShots\registrationPage11_03_2018_04_43_34.png'><img src'C:\eclipse-workspace\project\screenShots\registrationPage11_03_2018_04_43_34.png'height ='100' width='100'/></a>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="49940" started-at="2018-03-11T05:43:04Z" finished-at="2018-03-11T05:43:54Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="49940" started-at="2018-03-11T05:43:04Z" finished-at="2018-03-11T05:43:54Z">
      <class name="pageObjects.project.registration.TC002_verifyRegistrationFailed">
        <test-method status="PASS" signature="verifyRegistrationSeccessful()[pri:0, instance:pageObjects.project.registration.TC002_verifyRegistrationFailed@26f67b76]" name="verifyRegistrationSeccessful" duration-ms="6035" started-at="2018-03-11T16:43:29Z" finished-at="2018-03-11T16:43:35Z">
          <reporter-output>
            <line>
              <![CDATA[<a href='C:\eclipse-workspace\project\screenShots\registrationPage11_03_2018_04_43_34.png'><img src'C:\eclipse-workspace\project\screenShots\registrationPage11_03_2018_04_43_34.png'height ='100' width='100'/></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- verifyRegistrationSeccessful -->
      </class> <!-- pageObjects.project.registration.TC002_verifyRegistrationFailed -->
      <class name="pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials">
        <test-method status="PASS" signature="setUp()[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="setUp" is-config="true" duration-ms="13015" started-at="2018-03-11T16:43:04Z" finished-at="2018-03-11T16:43:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:pageObjects.project.registration.TC002_verifyRegistrationFailed@26f67b76]" name="setUp" is-config="true" duration-ms="11223" started-at="2018-03-11T16:43:17Z" finished-at="2018-03-11T16:43:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="6519" started-at="2018-03-11T16:43:35Z" data-provider="loginData" finished-at="2018-03-11T16:43:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[y]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="SKIP" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="1" started-at="2018-03-11T16:43:42Z" data-provider="loginData" finished-at="2018-03-11T16:43:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test Skipped
	at pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials.verifyLoginWithInvalidCradentials(TC001_verifyLoginWithInvalidCredentials.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="SKIP" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="0" started-at="2018-03-11T16:43:42Z" data-provider="loginData" finished-at="2018-03-11T16:43:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test Skipped
	at pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials.verifyLoginWithInvalidCradentials(TC001_verifyLoginWithInvalidCredentials.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="SKIP" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="0" started-at="2018-03-11T16:43:42Z" data-provider="loginData" finished-at="2018-03-11T16:43:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test Skipped
	at pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials.verifyLoginWithInvalidCradentials(TC001_verifyLoginWithInvalidCredentials.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="PASS" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="6186" started-at="2018-03-11T16:43:42Z" data-provider="loginData" finished-at="2018-03-11T16:43:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[y]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="SKIP" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="0" started-at="2018-03-11T16:43:48Z" data-provider="loginData" finished-at="2018-03-11T16:43:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test Skipped
	at pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials.verifyLoginWithInvalidCradentials(TC001_verifyLoginWithInvalidCredentials.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="PASS" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="5150" started-at="2018-03-11T16:43:48Z" data-provider="loginData" finished-at="2018-03-11T16:43:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[y]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="SKIP" signature="verifyLoginWithInvalidCradentials(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="verifyLoginWithInvalidCradentials" duration-ms="0" started-at="2018-03-11T16:43:48Z" data-provider="loginData" finished-at="2018-03-11T16:43:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ada@bab.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[data5575s]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[n]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Test Skipped]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Test Skipped
	at pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials.verifyLoginWithInvalidCradentials(TC001_verifyLoginWithInvalidCredentials.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithInvalidCradentials -->
        <test-method status="PASS" signature="endTest()[pri:0, instance:pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials@153f5a29]" name="endTest" is-config="true" duration-ms="1111" started-at="2018-03-11T16:43:53Z" finished-at="2018-03-11T16:43:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pageObjects.project.registration.TC002_verifyRegistrationFailed@26f67b76]" name="tearDown" is-config="true" duration-ms="85" started-at="2018-03-11T16:43:54Z" finished-at="2018-03-11T16:43:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pageObjects.project.homepage.TC001_verifyLoginWithInvalidCredentials -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
